// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAde7foV7KsrixAY69QHMejJsI5qGnHA3k',
    appId: '1:607676168991:android:c7d0c9c0186bfe04cb8e2a',
    messagingSenderId: '607676168991',
    projectId: 'iq-note-e121e',
    storageBucket: 'iq-note-e121e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8i9Y8RfNWPb7gGuf6Yfuf52cwXd0FKvo',
    appId: '1:607676168991:ios:445bfcc4a43d0e7dcb8e2a',
    messagingSenderId: '607676168991',
    projectId: 'iq-note-e121e',
    storageBucket: 'iq-note-e121e.appspot.com',
    androidClientId: '607676168991-5nig4atfl6orkl9s33ck679hmniikk1s.apps.googleusercontent.com',
    iosClientId: '607676168991-rtuvp6pqm4m3i422gc7j70d5ihtb8f69.apps.googleusercontent.com',
    iosBundleId: 'com.example.iqNote',
  );
}
